[package]
name = "rm-rf-hvcursos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.7"
serde = "1.0.133"
serde_json = "1.0.74"
reqwest = { version = "0.11.8", features = ["json"] }
